### ISSUE TITLE
New line in content

### ISSUE THREAD

**Issue by kpagnat** [jackdomleo7/Cooltipz.css#37]
Hi,

I love this library that allows to customizable how I handle my tooltips.
But it seems that the "aria-label" can't contains html code like `<br />` nor `\n` to indicate a new line in the tooltip.

Is that something that can be done ?

Thanks

**Comment by jackdomleo7** [comment]
Hi,

Interesting query. While my guess would have been to use `\n`, this does not work. After some research, it seems this is impossible since the intended purpose of HTML attributes is not to make something look pretty. It's for software to read, whether it be browsers, screenreaders, or whatever.

I hope this helps?

The only thing I can suggest is maybe taking a look at a JS tooltip library that renders tooltips in HTML elements rather than in pseudo-elements from HTML attributes via the CSS-only route. 🙂

**Comment by kpagnat** [comment]
Hi,

Thanks for your answer. I already test all kind of tooltip script and yours was a nice way to handle my tooltips.
I think I will just change the way I show my information :)

Best regards

**Comment by jackdomleo7** [comment]
Awesome! Thank you for the feedback too.
