### ISSUE TITLE
[BUG]: Important comment appears in the middle of the stylesheet rather than at the start

### ISSUE THREAD

**Issue by jackdomleo7** [jackdomleo7/Cooltipz.css#62]
# Bug Report

## Details of the bug

Cooltipz.css version: 2.0.0

Since v2.0.0, the below comment that should appear at the start of the stylesheet, now appears in the middle:

```css
/*! Cooltipz.css v2.0.0 | MIT License | github.com/jackdomleo7/Cooltipz.css */
```

## What is the expected result?
Important copyright comment appears at the very start of the stylesheet

## What is the actual result?
Important copyright comment appears somewhere in the middle of the stylesheet

## Acceptance criteria

- [ ] Make important copyright comment appear at the start of the stylesheet

## Why is fixing this bug important?

It's important to have the copyright at the beginning so it is easily visible.

**Comment by tannerdolby** [comment]
👋 @jackdomleo7 

As this issue eluded me in Checka11y.css, I'd like to take this on here and hopefully shed some light on how we can resolve it in Checka11y.css as well :)

**Comment by jackdomleo7** [comment]
That'd be really great! I can't figure it out 🤨

**Comment by tannerdolby** [comment]
Yeah its definitely not clear what is causing it. I think what could be happening is when Sass compiles the CSS, because Sass doesn't like comments at the start of files (it prefers at-rules to be at the topmost of each file, if any are used), this might be part of the issue of why the comments get moved from the top all the way down to wherever it was located, which I'm assuming is just being placed after the last stylesheet to be compiled and loaded into the main file. 

This is just a hunch, but I will investigate more thoroughly later tonight 😄
