### ISSUE TITLE
Newline

### ISSUE THREAD

**Issue by ray73864** [jackdomleo7/Cooltipz.css#81]
Is there anyway to get a newline into a tooltip?

I'm really loving the speed of css3 tooltips over the likes of tippyjs that I would normally use (Though I still need to use something like tippy or bootstraps tooltips if I want HTML in a tooltip), but for a lot of the basic stuff, this library works perfectly.

However, for some reason, I can't get ```&#013;``` to work.

In a regular 'title' attribute, I can do something like

```title="test&#013;test2"```

and the tooltip when it shows will have 'test2' on the line below 'test'.

**Comment by jackdomleo7** [comment]
Hi @ray73864, thanks for raising this bug. It seems the reason why it is not showing is because Cooltipz.css sets the property `white-space: nowrap;` on the tooltip. In devtools, if you set this to `white-space: pre;` or `white-space: pre-wrap;`, it should work.

As a quick fix, you create an overriding class, in the meantime I'm going to look at the best way to resolve this in this package.

**Comment by jackdomleo7** [comment]
This will be released in the next version release.

You can add `data-cooltipz-size="custom"` or `class="cooltipz--custom"` and use `&#xa;` in the `aria-label` to add custom newlines.

**Comment by jackdomleo7** [comment]
This is now released in [v2.2.0](https://github.com/jackdomleo7/Cooltipz.css/releases/tag/v2.2.0)

Please see https://cooltipz.jackdomleo.dev/#size
